package starter;

public class Token {
    public static String admin = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc5NDU1MDUsIm5hbWUiOiJTdXBlciBBZG1pbiIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjI3fQ.CfAjK4WfBFABFGfBI82zd9vz9R0kFXaqS5lXM2yJNII";
    public static String user = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODc5NTM2NTgsIm5hbWUiOiJUZXN0IDQiLCJyb2xlIjoiVXNlciIsInVzZXJfaWQiOjgwfQ.jpKv0UkKrQZrmY96SSbCjCIhU4CyaHbmK_dwqujEhyw";
}
